# Generated by Django 4.1.7 on 2023-03-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_remove_guide_device_remove_tutorial_device_appareils_and_more'),
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_devices',
            field=models.ManyToManyField(null=True, to='boutique.appareils'),
        ),
    ]
