# Generated by Django 4.1.7 on 2023-03-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_cat', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='category')),
            ],
        ),
    ]
