# Generated by Django 4.1.7 on 2023-03-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='device',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='device',
        ),
        migrations.CreateModel(
            name='Appareils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.category')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.marques')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='appareil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.appareils'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='appareil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.appareils'),
        ),
    ]
